version: '3.7'

services:
  nginx:
    image: {{ env.SERV_IMAGE }}
    # image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www/html:/var/www/html
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always
  
  prometheus:
    image: prom/prometheus:v2.45.2
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090

# source https://github.com/nginxinc/nginx-prometheus-exporter
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      - -nginx.scrape-uri=https://nginx/stub_status
    expose: 
      - 9113
    depends_on:
      - prometheus

  # source https://github.com/prometheus/node_exporter  
  # https://github.com/vegasbrianc/prometheus/
  prometheus-node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: prometheus-node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    privileged: true
    depends_on:
      - prometheus
    expose:
      - 9100

  # source https://grafana.com/docs/grafana/latest/installation/docker/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
  

