# https://habr.com/ru/articles/697206/

on:
  push:
    baranches: [ "master" ]

env:
  SERV_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/test-serv:${{ github.sha }}

jobs:
  build-image:
    environment: ittp
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build serv
      uses: docker/build-push-action@v3
      with:
        context: task4
        file: ./task4/Dockerfile
        push: true
        tags: ${{ env.SERV_IMAGE }}

  deploy:
    environment: ittp
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy COI VM
      id: deploy-coi
      uses: yc-actions/yc-coi-deploy@v1.0.1
      env:
        SERV_IMAGE: ${{ env.NGINX_IMAGE }}
        YC_VM_SSH: ${{ secrets.YC_VM_SSH }}
        YC_VM_USERNAME: ${{ secrets.YC_VM_USERNAME }}
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        VM-name: ${{ secrets.YC_VM_NAME }}
        vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        vm-cores: 2
        vm-platform-id: 'standard-v2'
        vm-memory: 1Gb
        vm-disk-size: 15Gb
        vm-core-fraction: 2
        vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
        docker-compose-path: './task4/docker-compose.yml'
        user-data-path: './task4/user-data.yml'
