# https://habr.com/ru/articles/697206/

on:
  push:
    baranches: [ "master" ]

env:
  SERV_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/test-serv:${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      # uses: actions/checkout@v3
      run: echo ${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ env.BACKEND_IMAGE }}